#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-A-0 -d I II III IV
bspc monitor HDMI-A-2 -d V VI VII VIII IX X
setxkbmap latam &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1 #2 #3 #1
bspc config window_gap          12 #3

bspc config focused_border_color "#44444"  #ffffff
bspc config presel_feedback_color "#2b4989"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#picom ---
picom -b &

#fondo de pantalla ---
#feh --bg-fill ~/.config/bspwm/fondos/dragonlore.jpeg
#feh --bg-fill ~/.config/bspwm/fondos/jdm.jpg
feh --bg-fill /home/levi/.config/bspwm/fondos/nice/atronaut.jpg

#polybar ---
$HOME/.config/polybar/launch.sh

xsetroot -cursor_name left_ptr &

corectrl &
bspc rule -a corectrl desktop='^X'



#picom --experimental-backends &
